# -*- coding: utf-8 -*-
"""Edge10 assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bJYwnrQ-cZOXmyJ1SlUmaFSBrNkrc3KQ
"""

import pandas as pd
import numpy as np
import random
import datetime
from sklearn.preprocessing import MinMaxScaler

players = ['Thibaut Courtois','Dani Carvajal','Éder Militão','David Alaba',
               'Jesús Vallejo','Nacho','Eden Hazard','Toni Kroos','Karim Benzema',
               'Luka Modrić','Marco Asensio','Marcelo','Andriy Lunin','Casemiro',
               'Federico Valverde','Luka Jović','Lucas Vázquez','Gareth Bale','Dani Ceballos','Vinícius Júnior']
Columns = ['Session_duration','Player_load','Number_of_ACC','Total_distance','RPE']
df = pd.DataFrame(columns=Columns)
distance = 0
for i in range(7020):
    session = random.randint(45,90)
    number_of_acc=random.randint(50,200)
    # distance= #random.randint(0,10000)
    rpe=random.randint(1,10)
    df.loc[i] =[session,'na',number_of_acc,distance,rpe]
playa=[]
players=['Thibaut Courtois','Dani Carvajal','Éder Militão','David Alaba','Jesús Vallejo','Nacho','Eden Hazard','Toni Kroos','Karim Benzema','Luka Modrić','Marco Asensio','Marcelo','Andriy Lunin','Casemiro','Federico Valverde','Luka Jović','Lucas Vázquez','Gareth Bale','Dani Ceballos','Vinícius Júnior'] 
for i in range(351):
    for k in players:
         playa.append(k)
print(len(playa))
df.insert(5,'player_name', value= playa,allow_duplicates= True)

df["Total_distance"] = get_standard_normal_value_in_range(0, 10000, 7020)

df.head()

from scipy.stats import pearsonr
from matplotlib import pyplot as plt

def get_standard_normal_value_in_range(min, max, size): 
  # get random no.
  arr = np.random.standard_normal(size)
  # min max Scale
  scaler = MinMaxScaler()
  scaled = scaler.fit_transform(arr[:,None])
  # scale to range
  return scaled * (max-min) + min

def get_player_load(df, source_col="Total_distance", tuner=0.2):
  scaler = MinMaxScaler()
  scaled = scaler.fit_transform(df[[source_col]])
  new_feature = scaled[:,0] + np.random.standard_normal(scaled.size) * tuner
  load_scaler = MinMaxScaler()
  feature = (load_scaler.fit_transform(new_feature[:,None]) * (300) + 300)
  r, _ = pearsonr(scaled[:,0], feature[:,0])
  return feature, r

new_feature, r = get_player_load(df, tuner=.25)

r

plt.scatter(df["Total_distance"], new_feature)

df['Player_load'] = new_feature

df.shape

dute=[]
fourteen =pd.date_range(start = '1-1-2014',end = '3-11-2014',freq='D') 
for i in range(20):
   for k in fourteen:
       dute.append(k)
fifteen = pd.date_range(start = '1-1-2015',end = '3-11-2015',freq='D') 
for i in range(20):
   for k in fifteen:
       dute.append(k)
sixteen=pd.date_range(start = '1-1-2016',end = '3-11-2016',freq='D')
for i in range(20):
   for k in sixteen:
      dute.append(k)
seventeen=pd.date_range(start = '1-1-2017',end = '3-11-2017',freq='D')
for i in range(20):
  for k in seventeen:
      dute.append(k)
eighteen=pd.date_range(start = '1-1-2018',end = '3-11-2018',freq='D')
for i in range(20):
   for k in eighteen:
       dute.append(k)
dute.sort(reverse=False)

df.insert(0,"Date",dute,allow_duplicates=True)

df.to_csv('Edge10_gsp.csv',index= False)